name: Publish to JSR

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: |
          VERSION=$(cat package.json | jq -r .version)
          CONFIG=$(cat jsr.json | jq ". + { \"version\": \"$VERSION\" }")
          echo $CONFIG | jq . > jsr.json
          npx jsr publish --allow-dirty
